# Generated by Django 2.0 on 2018-01-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180102_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='about',
        ),
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='business',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='account',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='account',
            name='website',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='user-uploads/'),
        ),
    ]
