# Generated by Django 2.0 on 2017-12-10 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171013_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='default_measure',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='business',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='measure',
        ),
        migrations.AddField(
            model_name='connection',
            name='notes',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='orders.Product'),
        ),
    ]
