# Generated by Django 2.0 on 2017-12-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171212_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_placed',
            new_name='requested_delivery',
        ),
    ]
