# Generated by Django 2.0 on 2017-12-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20171213_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Current'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
