# Generated by Django 2.0 on 2018-01-02 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180101_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requested_delivery',
            field=models.DateField(default=datetime.date(2018, 1, 9), verbose_name='requested delivery date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Current'), ('D', 'Delivered')], default='C', max_length=1),
        ),
    ]
