# Generated by Django 2.0 on 2018-01-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180102_2155'),
        ('orders', '0012_auto_20180102_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about',
            field=models.TextField(default=None, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='account',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='users.Account'),
        ),
        migrations.AddField(
            model_name='business',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='users.Picture'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='users.Picture'),
        ),
    ]
