# Generated by Django 2.0 on 2018-01-05 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180102_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requested_delivery',
            field=models.DateField(default=datetime.date(2018, 1, 12), verbose_name='requested delivery date'),
        ),
    ]
