# Generated by Django 2.0 on 2018-01-05 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180105_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='connection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Connection'),
        ),
    ]
