# Generated by Django 2.0 on 2018-01-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20180105_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tagline',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Current'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
