# Generated by Django 2.0 on 2018-01-06 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180105_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requested_delivery',
            field=models.DateField(default=datetime.date(2018, 1, 13), verbose_name='requested delivery date'),
        ),
    ]
